package com.example.shardingjdbcdemo.model;

import java.math.BigDecimal;

/**
 * @author eddie.lee
 */
public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.order_id
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.order_amount
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.order_status
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.user_id
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.order_id
     *
     * @return the value of t_order_1.order_id
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.order_id
     *
     * @param orderId the value for t_order_1.order_id
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.order_amount
     *
     * @return the value of t_order_1.order_amount
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.order_amount
     *
     * @param orderAmount the value for t_order_1.order_amount
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.order_status
     *
     * @return the value of t_order_1.order_status
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.order_status
     *
     * @param orderStatus the value for t_order_1.order_status
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.user_id
     *
     * @return the value of t_order_1.user_id
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.user_id
     *
     * @param userId the value for t_order_1.user_id
     *
     * @mbg.generated Wed Oct 28 14:10:26 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}